development:
  fedora:
    url: http://fedoraAdmin:fdminU1Uc@127.0.0.1:8080/fedora
  solr:
    url: http://127.0.0.1:8080/solr/development
test: &TEST  
  fedora:
    url: http://fedoraAdmin:fdminU1Uc@127.0.0.1:8080/fedora
  solr:
    url: http://localhost:8080/solr/test
production:
  fedora:
    url: http://fedoraAdmin:fdminU1Uc@your.production.server:8080/fedora
  solr:
    url: http://your.production.server:8080/solr 
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
                                        
